## Tactful Cloud Resource Template (http://tactful.cloud)
## Developer: @rosswickman (ross@tactful.cloud)
## Resource Provisioned: CloudWatch Alert
## Description: Deploys a CW Alert for a single instance with customizable metrics
---
AWSTemplateFormatVersion: "2010-09-09"
Description: CloudWatch Alarm for EC2 Instance

Metadata:

  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Instance Details
        Parameters:
          - ec2InstanceId

      - Label:
          default: Alert Details
        Parameters:
          - snsTopicArn

    ParameterLabels:
      ec2InstanceId:
        default: Instance ID
      snsTopicArn:
        default: SNS Topic ARN

Parameters:

  ec2InstanceId:
    Type: AWS::EC2::Instance::Id
    Description: ID of EC2 instance to monitor

  snsTopicArn:
    Type: String
    Description: ARN of the SNS topic to send alerts to.
    Default: "Paste ARN Here"

Resources:

  alarmEc2Cpu:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName:
      AlarmDescription:
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 90
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: InstanceId
        Value: !Ref ec2InstanceId
      AlarmActions:
        - !Ref snsTopicArn
      OKActions:
        - !Ref snsTopicArn

  alarmEc2Status:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName:
      AlarmDescription:
      MetricName: StatusCheckFailed
      Namespace: AWS/EC2
      Statistic: Maximum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
      - Name: InstanceId
        Value: !Ref ec2InstanceId
      AlarmActions:
        - !Ref snsTopicArn
      OKActions:
        - !Ref snsTopicArn
