## Tactful Cloud Resource Template (http://tactful.cloud)
## Developer: @rosswickman (ross@tactful.cloud)
## Resource Provisioned: IAM Role for EC2 CloudWatch Agent
## Description: Base role/profile required for CloudWatch monitoring and SSM
---
AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role - Instance Monitoring and SSM Inventory

Resources:

  roleBaseEc2:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ec2-cw-server-ssm
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore
        - !Sub arn:${AWS::Partition}:iam::aws:policy/CloudWatchAgentServerPolicy

  profileBaseEc2:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Ref roleBaseEc2
      Path: /
      Roles:
      - !Ref roleBaseEc2
