## Tactful Cloud Resource Template (http://tactful.cloud)
## Developer: @rosswickman (ross@tactful.cloud)
## Resource Provisioned: IAM Role for EC2 CloudWatch Agent
## Description: Base role/profile required for CloudWatch monitoring and SSM
## using a condition to deploy the desired role.
---
AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role - Instance Monitoring and SSM Inventory

Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: CloudWatch/SSM Role Details
      Parameters:
      - RoleType

    ParameterLabels:
      RoleType:
        default: Role Type
      RoleName:
        default: Role Name

Parameters:

  RoleType:
    Type: String
    Description: Which role to deploy (Server recommended default unless custom CloudWatch Config is required.)
    AllowedValues:
      - "Server"
      - "Admin"
      - "Both"
    Default: Server

  RoleName:
    Type: String
    Description: Name the role (resulting roles will be - {this input}-admin and/or {this input-server})
    Default: ec2-cw-ssm

Conditions:

  deployServer: !Or [ !Equals [!Ref RoleType, "Server"], !Equals [!Ref RoleType, "Both"] ]
  deployAdmin: !Or [ !Equals [!Ref RoleType, "Admin"],  !Equals [!Ref RoleType, "Both"] ]

Resources:

  roleBaseEc2Server:
    Condition: deployServer
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${RoleName}-server
      Description: Basic permissions to allow CloudWatch Logging and SSM Access
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore
        - !Sub arn:${AWS::Partition}:iam::aws:policy/CloudWatchAgentServerPolicy

  profileBaseEc2Server:
    Condition: deployServer
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Ref roleBaseEc2Server
      Path: /
      Roles:
      - !Ref roleBaseEc2Server

  roleBaseEc2Admin:
    Condition: deployAdmin
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${RoleName}-admin
      Description: Basic permissions to allow CloudWatch to create Logging Config and Store in SSM Parameter
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore
        - !Sub arn:${AWS::Partition}:iam::aws:policy/CloudWatchAgentAdminPolicy

  profileBaseEc2Admin:
    Condition: deployAdmin
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Ref roleBaseEc2Admin
      Path: /
      Roles:
      - !Ref roleBaseEc2Admin
