## Tactful Cloud Resource Template (http://tactful.cloud)
## Developer: @rosswickman (ross@tactful.cloud)
## Resource Provisioned: SNS Topic with Subscription
## Description: Topic to be used for sending CloudWatch Alerts
## Does not use KMS for encryption
---
AWSTemplateFormatVersion: "2010-09-09"
Description: SNS Topic & Email Subscription for CloudWatch Alerts

Metadata:

  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Notification Configuration
        Parameters:
          - emailAddress
          - ogApiKey

    ParameterLabels:
      emailAddress:
        default: Email Address
      ogApiKey:
        default: OpsGenie API Key

Parameters:

  emailAddress:
    Type: String
    Description: Primary Email address for all subscriptions
    Default: monitor@completeflight.com

  ogApiKey:
    Type: String
    Description: Primary Email address for all subscriptions
    Default: e3cfd782-4bce-481e-be8f-cfb9bfc2daf7

Resources:

  snsAlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      #checkov:skip=CKV_AWS_26:Ensure all data stored in the SNS topic is encrypted
      TopicName: EC2-CloudWatch-Alerts

  snsEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref emailAddress
      Protocol: email
      TopicArn: !Ref 'snsAlertTopic'

  snsOgSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Sub 'https://api.opsgenie.com/v1/json/cloudwatch?apiKey=${ogApiKey}'
      Protocol: https
      TopicArn: !Ref 'snsAlertTopic'

Outputs:

  snsAlertTopic:
    Description: 'SNS Alert Topic'
    Value: !Ref snsAlertTopic
    Export:
      Name: !Sub '${AWS::StackName}-snsEc2AlertTopic'
