## Tactful Cloud Resource Template (http://tactful.cloud)
## Developer: @rosswickman (ross@tactful.cloud)
## Resource Provisioned: SNS Topic with Subscription
## Description: Topic to be used for sending CloudWatch Alerts
---
AWSTemplateFormatVersion: "2010-09-09"
Description: SNS Topic & Email Subscription for CloudWatch Alerts

Metadata:

  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Notification Configuration
        Parameters:
          - emailAddress

    ParameterLabels:
      emailAddress:
        default: Email Address

Parameters:

  emailAddress:
    Type: String
    Description: Primary Email address for all subscriptions

Resources:

  snsAlertTopic:
    #checkov:skip=CKV_AWS_26:Ensure all data stored in the SNS topic is encrypted
    Type: AWS::SNS::Topic
    Properties:
      TopicName: EC2-CloudWatch-Alerts
      Subscription:
        - Endpoint: !Ref emailAddress
          Protocol: email

  ## use this for adding additional email subscriptions to this topic
  ## give a unique resource name for each additional subscription
  # snsTopicSubscription:
  #   Type: AWS::SNS::Topic
  #   Properties:
  #     TopicArn: !Ref snsAlertTopic
  #     Endpoint: #EmailAddress
  #     Protocol: email

Outputs:

  snsAlertTopic:
    Description: 'SNS Alert Topic'
    Value: !Ref snsAlertTopic
    Export:
      Name: !Sub '${AWS::StackName}-snsEc2AlertTopic'