---
name: Production Workflow

on:
  push:
    branches:
      - master

env:
  bucket-name: aws-solutions

jobs:
  superlinter:
    runs-on: ubuntu-latest
    env:
      RUN_LOCAL: true
    name: Super-Linter
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Run Superlinter
        id: superlinter
        uses: github/super-linter@v3.13.2

  checkov:
    runs-on: ubuntu-latest
    name: Checkov
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@master
        with:
          directory: cloudformation
          quiet: true

  cfn-nag:
    if: always()
    runs-on: ubuntu-latest
    name: Cfn-Nag
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: CFN-NAG
        uses: stelligent/cfn_nag@master
        with:
          input_path: cloudformation

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        DEST_DIR: ${{github.event.repository.name}}